name: Build MY.FeatureToggle

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2

        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 3.1.301

        - name: Install dependencies
          run: dotnet restore src/dotnet/MY.FeatureToggle.sln

        - name: Build
          run: dotnet build src/dotnet/MY.FeatureToggle.sln --configuration Release --no-restore
